---
sudo: false
language: c
os: linux
services:
  - docker

compiler: gcc
env:
  - GST=disabled DOCS=false VAPI=disabled
  - GST=enabled DOCS=true VAPI=enabled
# Do one build on clang
matrix:
  include:
    - sudo: false
      compiler: clang
      env: GST=enabled DOCS=false VAPI=disabled

before_install:
  - docker pull debian:bullseye
  - echo FROM debian:bullseye >Dockerfile
  - echo ADD . /root/ci >>Dockerfile
  - echo WORKDIR /root/ci >>Dockerfile
  - echo RUN apt-get update -qq >>Dockerfile
  - echo RUN apt-get install -qq -y bison gtk-doc-tools libgirepository1.0-dev \
    libgtk-3-dev meson texinfo valac xvfb >>Dockerfile
  - if test $GST != disabled; then
    echo RUN apt-get install -qq -y libgstreamer1.0-dev gstreamer1.0-tools \
      gstreamer1.0-plugins-bad gstreamer1.0-plugins-good >>Dockerfile;
    fi
  - echo ENV CFLAGS -fdiagnostics-color >>Dockerfile
  - echo RUN meson _build -Dgtk_doc=$DOCS -Dsound=$GST -Dvapi=$VAPI >>Dockerfile
  - echo RUN xvfb-run -a meson test -C _build >>Dockerfile

script:
  - docker build .

after_failure:
  - COMMIT=$(docker commit $(docker ps -l --format '{{.ID}}') | cut -f2 -d:)
  - docker run -it --security-opt label:disable $COMMIT test -f /root/ci/chimara-*/_build/meson-logs/testlog.txt && cat /root/ci/chimara-*/_build/meson-logs/testlog.txt
