---
sudo: false
language: c
os: linux
services:
  - docker

compiler: gcc
env:
  - DISTRO=debian:stretch GST=no
  - DISTRO=debian:stretch GST=gstreamer1.0
  - DISTRO=debian:jessie GST=gstreamer0.10
# Do one build on clang
matrix:
  include:
    - sudo: false
      dist: trusty
      compiler: clang
      env: DISTRO=debian:stretch GST=gstreamer1.0

before_install:
  - docker pull $DISTRO
  - echo FROM $DISTRO >Dockerfile
  - echo ADD . /root/ci >>Dockerfile
  - echo WORKDIR /root/ci >>Dockerfile
  - echo RUN apt-get update -qq >>Dockerfile
  - echo RUN apt-get install -qq -y bison gtk-doc-tools libgirepository1.0-dev \
    libgtk-3-dev texinfo texlive valac xvfb >>Dockerfile
  - if test $GST != no; then
    echo RUN apt-get install -qq -y lib$GST-dev $GST-tools $GST-plugins-bad \
      $GST-plugins-good >>Dockerfile;
    fi
  - echo ENV CFLAGS -fdiagnostics-color >>Dockerfile
  - echo RUN ./autogen.sh >>Dockerfile
  - echo RUN ./configure --enable-gtk-doc --with-xvfb-tests --with-sound=$GST >>Dockerfile
  - echo RUN make >>Dockerfile
  - echo RUN make check >>Dockerfile
  - echo RUN make distcheck >>Dockerfile

script:
  - docker build .

after_failure:
  - COMMIT=$(docker commit $(docker ps -l --format '{{.ID}}') | cut -f2 -d:)
  - docker run -it --security-opt label:disable $COMMIT test -f /root/ci/tests/unit/test-suite.log && cat /root/ci/tests/unit/test-suite.log
  - docker run -it --security-opt label:disable $COMMIT test -f /root/ci/chimara-*/_build/tests/unit/test-suite.log && cat /root/ci/chimara-*/_build/tests/unit/test-suite.log
