# New ports collection makefile for:   libchimara
# Date created:        30 November 2009
# Whom:                W. M. van Vliet
#
# $FreeBSD$
#

PORTNAME=      libchimara
PORTVERSION=   0.1
CATEGORIES=    devel
MASTER_SITES=  http://lassie.student.utwente.nl/chimara/
DISTNAME=     chimara-0.1

MAINTAINER=    w.m.vanvliet@student.utwente.nl
COMMENT=       A GTK widget that implements the GLK interface for interactive fiction.

USE_GNOME=     gtk20

GNU_CONFIGURE= yes
USE_GMAKE=     yes
USE_LDCONFIG=  ${PREFIX}/lib ${PREFIX}/lib/chimara


.include <bsd.port.mk>
