---
name: Build packages
"on":
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+'
jobs:
  tarball:
    name: Source package
    runs-on: ubuntu-latest
    steps:
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-good \
            gstreamer1.0-tools \
            gtk-doc-tools \
            libgirepository1.0-dev \
            libgstreamer1.0-dev \
            libgtk-3-dev \
            libunwind-dev \
            meson \
            valac

      - uses: actions/checkout@v2

      - name: configure
        run: meson _build

      - name: build
        run: meson dist -C _build --no-tests

      - uses: actions/upload-artifact@v3
        with:
          name: Source package
          path: _build/meson-dist/chimara-*.tar.xz
